SET S(SSS)  'Seasons in the simulation'                                                        
/                                                                                              
*S01                                                                                           
S02,S04,S06,S08,S10,S12,S14,S16,S18,S20,S22,S24,S26,S28,S30,S32,S34,S36,S38,S40,S42,S44,S46,S48,S50,S52
*S02,S15,S25                                                                                   
/;                                                                                             
